const
  LOGIN = 'LOGIN',
  LOG_OUT = 'LOG_OUT',
  SET_LOADING = 'SET_LOADING',
  SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  DELETE_USER = 'DELETE_USER',
  OPEN_NOTIFICATION = 'OPEN_NOTIFICATION',
  CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION',
  SET_ALERT = 'SET_ALERT',
  TOGGLE_ERROR_WINDOW_IS_OPEN = 'TOGGLE_ERROR_WINDOW_IS_OPEN',
  FETCH_FOUND_PETS = 'FETCH_FOUND_PETS',
  SET_FOUND_PETS_TO_STORE = 'SET_FOUND_PETS_TO_STORE',
  SET_LOST_PETS_TO_STORE = 'SET_LOST_PETS_TO_STORE',
  FETCH_LOST_PETS = 'FETCH_LOST_PETS'

export default {
  LOGIN,
  LOG_OUT,
  SET_LOADING,
  SET_IS_AUTHENTICATED,
  CLOSE_NOTIFICATION,
  LOGIN_SUCCESS,
  SET_FOUND_PETS_TO_STORE,
  FETCH_FOUND_PETS,
  DELETE_USER,
  OPEN_NOTIFICATION,
  SET_ALERT,
  TOGGLE_ERROR_WINDOW_IS_OPEN,
  SET_LOST_PETS_TO_STORE,
  FETCH_LOST_PETS
};
